// KODESH — Pinturas de las fiestas y del Shabat: estilo común y escenas.
// Se generan desde el admin con la API de imágenes de OpenAI (api/art-gen.js).
export const ART_STYLE = 'Classical oil painting on canvas, visible brushstrokes, Rembrandt-style chiaroscuro with warm golden light against deep midnight-blue shadows, palette of antique gold, ochre, umber and night blue. Historically accurate ancient Israel / first-century Judea: linen and wool robes, head coverings, stone houses, clay lamps. Reverent, quiet, cinematic. Tall vertical composition (2:3) for a phone screen: the main subject in the upper-middle of the frame, the lower third darker, calm and simple so text can be placed over it. No text, no letters, no Hebrew script, no halos, no crosses, no modern objects, no close-up faces looking at the viewer.';

export const ART_SCENES = {
  pesaj: 'Night in an ancient Israelite home in Egypt: through an arched stone window a full moon in a starry sky; on a rough wooden table below, roasted lamb, a stack of flat unleavened bread, bitter herbs, a clay cup of wine and a small oil lamp; a wooden staff and travel sandals beside the table; the doorposts of the open door faintly marked with blood from a hyssop branch.',
  matzot: 'Dawn exodus: women kneading flat unleavened dough in wooden troughs wrapped in cloaks on their shoulders, flat round bread baking on hot stones, a long line of families and animals leaving under a pale golden sky.',
  bikurim: 'Early spring sunrise over fields of young barley near Jerusalem: a priest in white linen lifting and waving a single sheaf of green-gold barley before the altar, soft smoke rising, farmers watching with baskets; an empty rock-cut tomb with its round stone rolled away glowing faintly in the distance.',
  shavuot: 'Golden wheat harvest at sunset in the hills of Judea: reapers with sickles, sheaves standing in rows, a young woman gleaning at the edge of the field, and in the distance Jerusalem on the hill; above, soft tongues of flame-like light in the evening sky.',
  terua: 'Twilight on the first day of the seventh month: a man on a stone rooftop in Jerusalem blowing a long curved ram\'s horn shofar toward the sky, a thin new crescent moon just visible above the western hills, people looking up from the streets below.',
  kipur: 'Inside the Holy of Holies seen from behind the high priest: the high priest in plain white linen garments, a censer of incense rising as a cloud, the golden ark faintly glowing in the smoke, the heavy embroidered veil torn from top to bottom letting golden light pour in; deep silence.',
  sukot: 'Harvest evening in Jerusalem: a booth made of palm branches and leafy boughs on a stone rooftop, fruit hanging from its roof, a family inside sharing a meal by lamplight, children holding palm, myrtle and willow branches with a citron; in the background the Temple court lit by enormous golden lampstands under the night sky.',
  shabat: 'Friday at sunset in the hills of Galilee: the sun setting over a winding river valley, golden rays breaking through the clouds, a thin crescent moon rising in the darkening sky; in the foreground a simple wooden table with two lit oil lamps, a round loaf of bread under a linen cloth and a clay cup of wine.',
};
export const ART_IDS = Object.keys(ART_SCENES);
export const artPrompt = id => `${ART_STYLE}\n\nScene: ${ART_SCENES[id]}`;
